alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: "standard"

server:
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 1
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - prometheus.ehbc.lab
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.ehbc.lab
