AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para la creación de la infraestructura necesaria para el despliegue de la aplicacion de productos

Parameters:
  BucketName:
    Description: Nombre del bucket S3
    Type: String

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: lm_troux_uid
          Value: 123

    S3BucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowCloudFrontAccessToS3
              Effect: Allow
              Principal:
                CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
              Action: 's3:GetObject'
              Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for S3 Bucket

      # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
      CloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties: 
          DistributionConfig:
            Enabled: true
            Origins:
              - DomainName: !GetAtt S3Bucket.DomainName
                Id: "${BucketName}Origin"
                S3OriginConfig:
                  OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
            DefaultCacheBehavior:
              TargetOriginId: !Sub "${BucketName}Origin"
              ViewerProtocolPolicy: redirect-to-https
              AllowedMethods:
                - GET
                - HEAD
              CachedMethods:
                - GET
                - HEAD
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              Compress: true
              ViewerCertificate:
                CloudFrontDefaultCertificate: true
            DefaultRootObject: index.html
          Tags: 
            - Key: lm_troux_uid
              Value: 123

Outputs:
  BucketName:
    Description: Nombre del bucket de S3
    Value: !Ref BucketName
  CloudFrontDistributionDomainName:
    Description: URL de la distribución de CloudFront
    Value: !GetAtt CloudFrontDistribution.DomainName