name: Upload Files to S3

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Upload files to S3
      run: |
        aws s3 cp kibernum/${{ vars.INDEX_NAME }} s3://${{ vars.S3_BUCKET_NAME }}/${{ vars.INDEX_NAME }}
        aws s3 cp kibernum/${{ vars.SCRIPT_NAME }} s3://${{ vars.S3_BUCKET_NAME }}/${{ vars.SCRIPT_NAME }}
