AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para la creación de la infraestructura necesaria para el despliegue de la aplicacion de productos

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: demo-bucket-productos
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Name
          Value: demo-bucket-productos
        - Key: lm_troux_uid
          Value: 123456

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

Outputs:
  BucketName:
    Description: Nombre del bucket de S3
    Value: !Ref S3Bucket
    Export:
      Name: MyS3BucketName